---
# tasks file for docker
- name: "Install packages to allow apt to use a repository over HTTPS"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Wait for APT Lock
  ansible.builtin.shell: |
    while sudo fuser /var/lib/{{ item }} >/dev/null 2>&1; do sleep 5; done;
  loop:
    - dpkg/lock
    - dpkg/lock-frontend
    - apt/lists/lock
  retries: 5
  delay: 3

- name: Install requirements for docker compose
  ansible.builtin.pip:
    name: "{{ python_moduls }}"

- name: Add Docker’s official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: "0644"

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: "Install Docker Engine, containerd, and Docker Compose"
  ansible.builtin.apt:
    name: "{{ dpackages }}"
    state: present

- name: "Enable docker service"
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Copy file with tests
  ansible.builtin.copy:
    src: test.py
    dest: /tmp/
    mode: "0755"

- name: Start test
  ansible.builtin.command: pytest -v /tmp/test.py
